export type Location = {
    latitude: number;
    longitude: number;
    altitude: number;
};

export type ScanMesh = {
    dtHdScanId: string;
    status: string;
    siteName: string;
    source: string | null;
    platform: string | null;
    thumbnail: string;
    thumbnailUrl: string;
    createdDate: string;
    updatedDate: string;
    scanLocation: Location;
    refX: number;
    refY: number;
    refZ: number;
    floor: number;
    scanMeshUrl: string;
    vpsHdSite: string | null;
    mediaFiles: string | null;
    mediaStatus: string;
    dtScanStatus: string;
    anchorStatus: string;
    category: string;
    spawnPositionX: number;
    spawnPositionY: number;
    spawnPositionZ: number;
    spawnHeading: number;
    vpsAnchorId: string | null;
    vpsTrackingId: string | null;
    scanArea: number;
    bBoxCenterX: number | null;
    bBoxCenterY: number | null;
    bBoxCenterZ: number | null;
    bBoxLength: number | null;
    bBoxWidth: number | null;
    bBoxHeight: number | null;
    bBoxOrientationYaw: number | null;
    needsRescan: boolean;
    scanSize: string;
    cesiumAssetId: string;
    sourceMetaAppId: string | null;
    sourceMetaAppVersion: string | null;
    scanGroup: string | null;
    scanNotes: string | null;
};

export type Version = {
    version: number;
    status: string;
    cesiumAssetId: string;
    updatedDate: string;
    lastPublishedDate: string;
    spawnPositionX: number;
    spawnPositionY: number;
    spawnPositionZ: number;
    spawnHeading: number;
};

export type DigitalTwin = {
    dtHdId: string;
    userId: string;
    appId: string;
    clientMnemonic: string;
    externalUserId: string;
    name: string;
    location: Location;
    refX: number;
    refY: number;
    refZ: number;
    createdDate: string;
    updatedDate: string;
    fileSizeBytes: number;
    spawnPositionX: number;
    spawnPositionY: number;
    spawnPositionZ: number;
    spawnHeading: number;
    isIndoor: boolean;
    isPublic: boolean;
    scanMeshes: ScanMesh[];
    enhancedMesh: string;
    assets: any[];
    versions: Version[];
    reflectionProbeInfoUrl: string | null;
    dtEnvironmentUrl: string | null;
    cesiumAssetId: string;
};
