name: Go Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21' # Use the Go version of your choice

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build binary for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o unrpa-linux-amd64 .

      - name: Build binary for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o unrpa-windows-amd64.exe .

      - name: Build binary for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o unrpa-macos-amd64 .

      - name: Create a Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ github.ref }}

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            unrpa-linux-amd64
            unrpa-macos-amd64
            unrpa-windows-amd64.exe
