name: Go Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev build-essential libxxf86vm-dev jq

      - name: Build binary for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o unrpa-linux-amd64 .

      #      - name: Build binary for Windows
      #        run: |
      #          GOOS=windows GOARCH=amd64 go build -o unrpa-windows-amd64.exe .

      # Use a single action for creating the release and uploading assets
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            unrpa-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update resources.json
        run: |
          TMP_BRANCH_NAME=${{ github.ref_name }}-$(date +%s)$RANDOM
          git checkout -b ${TMP_BRANCH_NAME}
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          git merge --no-ff ${TMP_BRANCH_NAME}
          git branch -D ${TMP_BRANCH_NAME}
          
          GOOS=js GOARCH=wasm go build -o wasm/unrpa.wasm wasm/main.go

          # Prepare the download URL
          LINUX_EXE="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/unrpa-linux-amd64"
          
          # Update resources.json
          echo "{\"linux_exe\": \"${LINUX_EXE}\"}"
          echo "{\"linux_exe\": \"${LINUX_EXE}\"}" > resources.json
          
          # Configure git
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Commit and push changes
          git add resources.json
          git add wasm/unrpa.wasm
          git commit -m 'Update resources.json with latest release URLs'
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
