name: Go Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      #      - name: Cache Node.js modules
      #        uses: actions/cache@v2
      #        with:
      #          # npm cache files are stored in `~/.npm` on Linux/macOS
      #          path: ~/.npm
      #          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
      #          restore-keys: |
      #            ${{ runner.OS }}-node-
      #            ${{ runner.OS }}-

      - name: Install Dependencies
        run: |
          cd unrpapp
          npm install
          npm run build

      - name: Build
        run: |
          
          # compile worker.js separately
          # compile them before project so .js would present in public directory of project before main build
          tsc --project workers.tsconfig.json
          
          # build react
          npm install
          npm run build
          
          # compile wasm
          GOOS=js GOARCH=wasm go build -o wasm/unrpa.wasm wasm/main.go
          cp wasm/unrpa.wasm build
          
          # substitute version
          GIT_TAG=$(git describe --tags)
          GIT_SHORT_HASH=$(git rev-parse --short HEAD)
          NEW_TAG="${GIT_TAG}-${GIT_SHORT_HASH}" 
          FIND_PATTERN="ITWILLBEREPLACEDWITHVERSION"
          find ./build -type f -exec sed -i "s/$FIND_PATTERN/$NEW_TAG/g" {} \;





      - name: Publish build directory to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:

          # Optional. Default value "." means the root directory of your project will be published.
          # You can use whatever directory your project uses, for example "wwwroot".
          # Such a directory does *not* have to already exist in your repo,
          # it could be an output directory created dynamically by your static website builder.
          source-directory: build

          # Optional. Default value "gh-pages".
          # It specifies the temporary branch which hosts the static website.
          # Each build will OVERWRITE this branch.
          target-branch: gh-pages

